gifHex = {0: ['47 49 46 38 39 61', 'Header'],
            1: ['39 61', 'Version. May differ.'],
            2: ['03 00', 'Logical screen width in pixels.'],
            3: ['03 00', 'Logical screen heigth in pixels.'],
            4: ['F7', 'GCT follows for 256 colors with resolution 3x8 bits/primary, the lowest 3 bits represent the bit'
                      ' depth minus 1, the highest true bit means that the GCT is present.'],
            5: ['',
                ''],
            6: ['',
                ''],
            7: ['',
                ''],
            8: ['',
                ''],
            9: ['',
                '']}

template = {0: ['', ''],
            1: ['',
                ''],
            2: ['',
                ''],
            3: ['',
                ''],
            4: ['',
                ''],
            5: ['',
                ''],
            6: ['',
                ''],
            7: ['',
                ''],
            8: ['',
                '']}